### ISSUE TITLE
Wrong detection

### ISSUE THREAD

**Issue by Julienraptor01** [zomabies/RestoreChatLinks#4] opened 2023-11-08 20:38 UTC
As shown right below, it only picked up https://imgur.com instead of https://imgur.com/iSsSDA0
![image](https://github.com/zomabies/RestoreChatLinks/assets/49841713/d78ab610-8061-4f7e-b923-80524e0a03ed)

**Comment by zomabies** [comment] 2023-11-11 08:07
Which version that you are currently using?

**Comment by Julienraptor01** [comment] 2023-11-11 09:10
> Which version that you are currently using?

I'm using 1.19.2-0.1.4

**Comment by zomabies** [comment] 2023-11-11 13:12
Please reproduce the issue using this version below and upload `latest.log`.
[RestoreChatLinks-1.19.2-0.1.4-debug.zip](https://github.com/zomabies/RestoreChatLinks/files/13325547/RestoreChatLinks-1.19.2-0.1.4-debug.zip) (rename .zip to .jar).

**Comment by zomabies** [comment] 2023-11-20 17:08
@Julienraptor01, is the issue still persists? I'm unable to reproduce it in 1.19.2 dev environment below.

![test](https://github.com/zomabies/RestoreChatLinks/assets/26372880/38c4dd1b-176c-4af6-b0a0-f86ed84716dc)

**Comment by Julienraptor01** [comment] 2023-11-20 17:22
Oh sorry i've completly forgot to test, i had a lot of other stuff, i'll try it rn and i'll tell you

**Comment by Julienraptor01** [comment] 2023-11-20 17:32
seems to work fine for me too 👍

**Comment by Julienraptor01** [comment] 2023-11-20 18:01
wait i'm confused cause i decompiled the mod and i see you made no change except logging stuff
however i don't manage to reproduce the issue anymore 😕

**Comment by Julienraptor01** [comment] 2023-11-20 18:25
ok so weirdly when i'm on hypixel it works half of the time and break half of the time, when i'm in solo, it doesn't work at all and when i'm other servers it sometimes work and sometimes doesn't so i'll try to see if it's not a mod conflict just in case
seems to be a very weird issue

**Comment by zomabies** [comment] 2023-11-20 19:40
I have released 1.19.2-0.1.5 on Modrinth, update to this version and enable `debugMessage` in the config file.

> ok so weirdly when i'm on hypixel it works half of the time and break half of the time, when i'm in solo, it doesn't work at all and when i'm other servers it sometimes work and sometimes doesn't so i'll try to see if it's not a mod conflict just in case seems to be a very weird issue

Please attach the log file (with `debugMessage` enabled) when that happen.

> wait i'm confused cause i decompiled the mod and i see you made no change except logging stuff however i don't manage to reproduce the issue anymore 😕

Yes, I added logging only to obtain the raw message for debugging.

**Comment by zomabies** [comment] 2023-12-17 17:48
Closing, as this is potentially caused by other mods and no mod list/logs were given.
If it happens again, feel free to open a new issue with all the relevant information.

**Closed as not planned by zomabies** 2023-12-17 17:48 UTC
